---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "econplaza-frontend-svc"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
      name: "http"
  selector:
    app: "econplaza-frontend"
  type: "NodePort"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "staging-econplaza-frontend-svc"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: "TCP"
    name: "http"
  selector:
    app: "staging-econplaza-frontend"
  type: "NodePort"