# Generated by Django 3.2.8 on 2021-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plazas", "0002_auto_20211128_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Post's Total Views (Computed)"
            ),
        ),
    ]
