# Generated by Django 3.2.8 on 2021-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plazas", "0003_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="last_computed",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Last modified timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="last_computed",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Last modified timestamp"
            ),
        ),
    ]
