# Generated by Django 3.2.8 on 2022-01-31 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plazas", "0004_alter_post_comment_last_computed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[("OP", "Owner"), ("AD", "Admin"), ("MB", "Member")],
                default="MB",
                max_length=2,
                verbose_name="Member Type",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="plaza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plazas.plaza",
                verbose_name="Plaza Membership's Plaza",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Plaza Membership's User",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("user", "plaza"), name="no_duplicate_memberships"
            ),
        ),
    ]
