# Generated by Django 3.2.8 on 2022-02-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plazas', '0005_add_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32, verbose_name="Tag's Slug")),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at timestamp')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'plazas'), ('model', 'plaza')), models.Q(('app_label', 'plazas'), ('model', 'post')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'content_type', 'object_id'), name='no_duplicate_tags'),
        ),
    ]
