# Generated by Django 3.2.8 on 2022-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plazas", "0006_add_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plaza",
            name="slug",
            field=models.SlugField(
                max_length=32, unique=True, verbose_name="Plaza's Slug"
            ),
        ),
    ]
