# Generated by Django 3.2.8 on 2022-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazas', '0006_add_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plaza',
            constraint=models.UniqueConstraint(fields=('slug',), name='slugs_must_be_unique'),
        ),
    ]
