# Generated by Django 3.2.8 on 2022-04-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plazas", "0007_alter_plaza_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="plazas.comment",
                verbose_name="Comment's Parent Comment",
            ),
        ),
    ]
