variables:
  DOCKER_REPO: "europe-west2-docker.pkg.dev"

build-docker-image:
  image: google/cloud-sdk:latest 
  stage: build
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$DOCKER_REPO
    - cd backend
    - docker build -t $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID

deploy-service:
  image: google/cloud-sdk:latest
  stage: deploy
  script:
    - cd backend
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - sed -i 's+<<DOCKER_IMAGE>>+$DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID+g' google.yaml
    - gcloud container clusters get-credentials econplaza
    - kubectl apply -f google.yaml
