variables:
  DOCKER_REPO: "docker.sambebbington.co.uk:4999"
  DOCKER_USER: $DOCKER_USER
  DOCKER_PASSWORD: $DOCKER_PASSWORD

stages:
  - build
  - staging
  - production

build-backend-docker-image:
  image: docker:19.03.12 
  stage: build
  script:
    - cd backend
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REPO
    - docker build -t $DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID

build-frontend-docker-image:
  stage: build
  script:
    - cd frontend
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REPO
    - docker build -t $DOCKER_REPO/econplaza/frontend:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/econplaza/frontend:$CI_PIPELINE_ID

deploy-staging:
  image: byrnedo/alpine-curl:0.1.8 
  stage: staging
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-staging/$CI_PIPELINE_ID

deploy-frontend-staging:
  image: byrnedo/alpine-curl:0.1.8
  stage: staging
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-frontend-staging/$CI_PIPELINE_ID

deploy-production:
  image: byrnedo/alpine-curl:0.1.8
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-production/$CI_PIPELINE_ID

deploy-frontend-production:
  image: byrnedo/alpine-curl:0.1.8
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-frontend-production/$CI_PIPELINE_ID

