variables:
  DOCKER_REPO: "docker.sambebbington.co.uk:4999"
  DOCKER_USER: $DOCKER_USER
  DOCKER_PASSWORD: $DOCKER_PASSWORD

stages:
  - build
  - staging
  - production

build-backend-docker-image:
  image: docker:19.03.12
  stage: build
  script:
    - cd backend
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REPO
    - docker build -t $DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID

build-frontend-docker-image:
  stage: build
  script:
    - cd frontend
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REPO
    - docker build -t $DOCKER_REPO/econplaza/frontend:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/econplaza/frontend:$CI_PIPELINE_ID

deploy-api-staging:
  image: alpine/curl:3.14
  stage: staging
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-staging/$CI_PIPELINE_ID
    - sleep 5
    - /bin/sh .deployment/deploy-check.sh econplaza-api-staging
  only:
    - master

deploy-frontend-staging:
  image: alpine/curl:3.14
  stage: staging
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-frontend-staging/$CI_PIPELINE_ID
    - sleep 5
    - /bin/sh .deployment/deploy-check.sh econplaza-frontend-staging
  only:
    - master

deploy-api-production:
  image: alpine/curl:3.14
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-production/$CI_PIPELINE_ID
    - sleep 5
    - /bin/sh .deployment/deploy-check.sh econplaza-api-production
  when: manual
  only:
    - master

deploy-frontend-production:
  image: alpine/curl:3.14
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-frontend-production/$CI_PIPELINE_ID
    - sleep 5
    - /bin/sh .deployment/deploy-check.sh econplaza-frontend-production
  when: manual
  only:
    - master

