variables:
  DOCKER_REPO: "europe-west2-docker.pkg.dev"

stages:
  - build
  - staging
  - production

build-docker-image:
  image: google/cloud-sdk:latest 
  stage: build
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$DOCKER_REPO
    - cd backend
    - docker build -t $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID .
    - docker push $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID

deploy-staging:
  image: google/cloud-sdk:latest
  stage: staging
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-staging/$CI_PIPELINE_ID
  only:
    - master

deploy-production:
  image: google/cloud-sdk:latest
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-api-production/$CI_PIPELINE_ID
  when: manual
  only:
    - master

deploy-frontend-production:
  image: alpine/curl:3.14
  stage: production
  script:
    - curl -i http://192.168.0.15:9999/blue-green/econplaza-frontend-production/$CI_PIPELINE_ID
  when: manual
  only:
    - master

