variables:
  DOCKER_REPO: "https://europe-west2-docker.pkg.dev"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.11-dind

build-docker-image:
  image: google/cloud-sdk:latest
  stage: Build
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - docker login -u _json_key_base64 --password-stdin https://$DOCKER_REPO < gcloud-service-key.json
    - cd backend
    - docker build -t $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID
    - docker push $DOCKER_REPO/$GCP_PROJECT_ID/econplaza/app:$CI_PIPELINE_ID

deploy-service:
  image: google/cloud-sdk:latest
  stage: Deploy
  script:
    - cd backend
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - sed -i 's+{DOCKER_IMAGE}+$DOCKER_REPO/econplaza/app:$CI_PIPELINE_ID+/g' google.yaml
    - kubectl apply -f google.yaml
