# Generated by Django 3.2.8 on 2021-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_computed",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Last modified timestamp"
            ),
        ),
    ]
