# Generated by Django 3.2.8 on 2021-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_last_computed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vouch',
            constraint=models.UniqueConstraint(fields=('voucher', 'vouchee'), name='unique_vouch'),
        ),
    ]
