# Generated by Django 3.2.8 on 2021-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_no_duplicate_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vouch",
            name="voucher_and_vouchee_cannot_be_same",
        ),
    ]
