# Generated by Django 3.2.8 on 2022-01-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_vouch_not_same"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="global_anonymous",
            field=models.BooleanField(
                default=0, verbose_name="Profile's Anonymous Flag"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profile's related user",
            ),
        ),
    ]
