# Generated by Django 3.2.8 on 2022-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_vouch_not_same"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="global_anonymous",
            field=models.BooleanField(
                default=0, verbose_name="Profile's Anonymous Flag"
            ),
        ),
    ]
