# Generated by Django 3.2.8 on 2022-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_fix_single_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institutional_affiliation",
            field=models.CharField(
                max_length=64, null=True, verbose_name="User's main institution"
            ),
        ),
    ]
