openapi: 3.1.0
info:
  title: econplaza_api
  version: '1.0'
  summary: EconPlaza Restfull API
  description: API implemented using django rest framework.
servers:
  - url: 'http://127.0.0.1:8000/api'
