# Generated by Django 3.2.8 on 2021-11-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsements', models.PositiveBigIntegerField(default=0, verbose_name="User's endorsements (Computed)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at timestamp')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label', verbose_name="User's label")),
            ],
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Endorsement's endorser"),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label', verbose_name="Endorsement's label"),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
