# Generated by Django 3.2.8 on 2021-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_auto_20211128_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endorsement",
            name="last_computed",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Last modified timestamp"
            ),
        ),
    ]
